apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vp-proxy-ca-read-ingress
  namespace: openshift-ingress-operator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["router-ca"]
    verbs: ["get"]
