{{- if and (eq .Values.managedClusterCaSource "spokePush") .Values.acm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vpProxyCa.fullname" . }}-spoke-push-includes
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  namespace.yaml: |
{{ .Files.Get "files/spoke-push/namespace.yaml" | indent 4 }}
  serviceaccount.yaml: |
{{ .Files.Get "files/spoke-push/serviceaccount.yaml" | indent 4 }}
  role-trust.yaml: |
{{ .Files.Get "files/spoke-push/role-trust.yaml" | indent 4 }}
  rolebinding-trust.yaml: |
{{ .Files.Get "files/spoke-push/rolebinding-trust.yaml" | indent 4 }}
  role-ingress.yaml: |
{{ .Files.Get "files/spoke-push/role-ingress.yaml" | indent 4 }}
  rolebinding-ingress.yaml: |
{{ .Files.Get "files/spoke-push/rolebinding-ingress.yaml" | indent 4 }}
  cronjob.yaml: |
{{ .Files.Get "files/spoke-push/cronjob.yaml" | indent 4 }}
  build-manifestwork.sh: |
{{ .Files.Get "files/spoke-push/build-manifestwork.sh" | indent 4 }}
  cron.sh: |
{{ .Files.Get "files/spoke-push/cron.sh" | indent 4 }}
{{- end }}
