apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vpProxyCa.fullname" . }}-script
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  gather-and-distribute-ca.sh: |
{{ .Files.Get "files/gather-and-distribute-ca.sh" | indent 4 }}
