{{- if .Values.cronJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "vpProxyCa.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  suspend: {{ .Values.cronJob.suspend }}
  schedule: {{ .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "vpProxyCa.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
{{ include "vpProxyCa.gatherContainer" . | trim | indent 12 }}
          volumes:
{{ include "vpProxyCa.gatherVolumes" . | trim | indent 12 }}
{{- end }}
