{{- if .Values.eso.export.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vpProxyCa.esoExportServiceAccountName" . }}
  namespace: {{ include "vpProxyCa.esoExportNamespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: eso-export
{{- end }}
