{{- if .Values.syncJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vpProxyCa.fullname" . }}-sync
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 7200
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "vpProxyCa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
{{ include "vpProxyCa.gatherContainer" . | trim | indent 8 }}
      volumes:
{{ include "vpProxyCa.gatherVolumes" . | trim | indent 8 }}
{{- end }}
