{{- if and .Values.policy.enabled .Values.acm.enabled .Values.policy.createPlacement .Values.policy.placementRef.name }}
{{- $ns := include "vpProxyCa.policyWorkspaceNamespace" . }}
{{- $placementName := .Values.policy.placementRef.name }}
{{- $clusterSets := .Values.policy.placement.clusterSets | default (list "global") }}
{{- if .Values.policy.createManagedClusterSetBindings }}
{{- range $clusterSets }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ . | quote }}
  namespace: {{ $ns }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  clusterSet: {{ . | quote }}
{{- end }}
{{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName | quote }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterSets:
{{- range $clusterSets }}
    - {{ . | quote }}
{{- end }}
{{- end }}
