{{- if and .Values.trustManager.enabled .Values.trustManager.byNamespaceNameBundle.enabled }}
{{- $cfg := .Values.trustManager.byNamespaceNameBundle }}
{{- $bundleName := include "vpProxyCa.trustBundleName" . }}
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ $bundleName }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $cfg.argoCDSyncWave | default .Values.trustManager.bundle.argoCDSyncWave | quote }}
  labels:
    app.kubernetes.io/name: {{ include "vpProxyCa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: trust-bundle-by-namespace-name
spec:
  sources:
{{ include "vpProxyCa.trustBundleSources" . | nindent 4 }}
  target:
    configMap:
      key: {{ .Values.trustManager.targetKey | quote }}
    namespaceSelector:
{{ include "vpProxyCa.trustBundleNamespaceSelector" . | indent 6 }}
{{- end }}
